#!/usr/bin/env python3
"""Compile authored YAML catalogs into committed Go/browser assets (development only)."""
import argparse
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
LOCALES = ("en-US", "pt-BR")
PLACEHOLDER = re.compile(r"%\{([a-z_]+)\}")


class CatalogLoader(yaml.SafeLoader):
    """Reject duplicate keys rather than silently dropping a translation."""


def mapping(loader, node):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node)
        if not isinstance(key, str) or key in result:
            raise ValueError(f"Invalid or duplicate key: {key!r}")
        result[key] = loader.construct_object(value_node)
    return result


CatalogLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, mapping)


def flatten(value, prefix=""):
    result = {}
    if not isinstance(value, dict) or not value:
        raise ValueError(f"Expected a non-empty mapping at {prefix}")
    for key, entry in value.items():
        if not re.fullmatch(r"[a-z][a-z0-9_]*", key):
            raise ValueError(f"Invalid key: {key}")
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(entry, dict):
            result.update(flatten(entry, path))
        elif isinstance(entry, str) and entry:
            # Catalogs contain plain text only. Escaping remains the renderer's job.
            if any(char in entry for char in "<>`") or "${" in entry:
                raise ValueError(f"Markup is not allowed: {path}")
            result[path] = entry
        else:
            raise ValueError(f"Expected a non-empty string at {path}")
    return result


def compile_catalogs():
    catalogs = {}
    for locale in LOCALES:
        source = yaml.load((ROOT / "locales" / f"{locale}.yml").read_text(), Loader=CatalogLoader)
        if not isinstance(source, dict) or list(source) != [locale]:
            raise ValueError(f"Expected a single {locale} root")
        catalogs[locale] = flatten(source[locale])
    base = catalogs[LOCALES[0]]
    for locale, catalog in catalogs.items():
        if catalog.keys() != base.keys():
            raise ValueError(f"Translation keys differ: {locale}: {catalog.keys() ^ base.keys()}")
        for key, message in catalog.items():
            if set(PLACEHOLDER.findall(message)) != set(PLACEHOLDER.findall(base[key])):
                raise ValueError(f"Placeholders differ: {locale}.{key}")
            if key.endswith(".one") and key[:-4] + ".other" not in catalog:
                raise ValueError(f"Missing plural fallback: {key}")
    payload = json.dumps(catalogs, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    return {
        ROOT / "internal/httpapi/locales/catalogs.json": payload,
        ROOT / "internal/httpapi/ui/catalogs.mjs": "// Generated by scripts/compile_locales.py. Do not edit.\n// prettier-ignore\nexport default " + payload.rstrip() + ";\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in compile_catalogs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Outdated catalog: {path.relative_to(ROOT)}; run scripts/compile_locales.py")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
